### ISSUE TITLE
`Stop` does not properly wait for the server to close

### ISSUE THREAD

**Issue by dcherman** [gajus/iapetus#3]
Thanks for providing this lib, I was about to write something like this when I saw you mention this in the k8s slack channel :)

Was looking through the code and noticed that the `stop` method does not properly wait for the server to close since no callback is provided.  Since the method was marked `async`, it seems like you had intended for it to wait.

https://github.com/gajus/iapetus/blob/7efdbaccc6537ae74f9cbfd5140cb05d89b7c8d4/src/factories/createIapetus.js#L122-L124

**Comment by gajus** [comment]
https://github.com/gajus/lightship/issues/5

**Comment by dcherman** [comment]
Hey, this wasn't actually a duplicate, this lib has the same issue per that piece of code that I linked :)
